apiVersion: v2
name: istiod-remote
version: 1.13.3-tetrate-v0
appVersion: 1.13.3-tetrate-v0
tillerVersion: ">=2.7.2"
description: Helm chart for a remote cluster using an external istio control plane
keywords:
  - istio
  - external-istiod
sources:
  - http://github.com/istio/istio
engine: gotpl
icon: https://istio.io/latest/favicons/android-192x192.png
