name: set-build-env-vars
description: 'Set build environment variables based on the event type'
runs:
  using: "composite"
  steps:
    - if: ${{ github.ref_type == 'tag' }}
      name: Set release-related environment variables
      shell: bash
      run: |
        # Set version value for release builds.
        echo "RELEASE_TAG=${GITHUB_REF_NAME}" >> "$GITHUB_ENV"
        # For backwards compatibility (e.g., scripts expecting CircleCI variables).
        echo "CIRCLE_TAG=${GITHUB_REF_NAME}" >> "$GITHUB_ENV"
        # Use a unique tag for images built from a tag push.
        echo "TAG=release-${GITHUB_REF_NAME}-${GITHUB_SHA}" >> "$GITHUB_ENV"
    
    - if: ${{ github.base_ref != null }}
      name: Set environment variables for pull requests
      shell: bash
      run: |
        # Construct a tag for PR builds using PR number and commit SHA.
        echo "CIRCLE_SHA1=pr-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}" >> "$GITHUB_ENV"
        echo "CIRCLE_BRANCH=${GITHUB_HEAD_REF}" >> "$GITHUB_ENV"
    
    - if: ${{ github.base_ref == null && github.ref_type != 'tag' }}
      name: Set environment variables for direct pushes
      shell: bash
      run: |
        echo "CIRCLE_SHA1=push-${GITHUB_SHA}" >> "$GITHUB_ENV"
        echo "CIRCLE_BRANCH=${GITHUB_REF_NAME}" >> "$GITHUB_ENV"
